version: "3.8"
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
  backend:
    image: backend
    build: ./vanRestaurantBackend
    ports:
      - "80:80"
    networks:
      - mern-app      
    depends_on:
      - mongodb
  frontend:
    image: frontend
    build: ./vanRestaurantFrontend
    ports:
      - "3000:3000"
    networks:
      - mern-app
    stdin_open: true
    depends_on:
      - backend
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
    