apiVersion: apps/v1
kind: Deployment
metadata:
  name: nearby-frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nearby-frontend
  template:
    metadata:
      labels:
        app: nearby-frontend
    spec:
      containers:
        - name: nearby-ecr-frontend
          image: 132619210333.dkr.ecr.us-west-1.amazonaws.com/nearby-repo:frontend
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
